apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fyp-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: fyp-app
    repoURL: https://github.com/yuemanwai/jp-academy-k8s-manifest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
