apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 46.1.0       # 指定 Helm chart 版本
    helm:
      releaseName: monitoring     # Helm release 名稱
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # 呢條 JSON Pointer 會叫 ArgoCD 忽略 metadata.annotations 嘅所有差異
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    # name: prometheuses.monitoring.coreos.com
    jsonPointers:
    - /metadata/annotations
