apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jp.fullname" . }}-init-db
  labels:
    {{- include "jp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: {{ .Values.job.backoffLimitCount }}
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "python init_db.py && python test_data.py"]
        env:
          - name: DB_HOST
            value: {{ include "jp.fullname" . }}-db.{{ .Release.Namespace }}.svc.cluster.local
          - name: DB_PORT
            value: "{{ .Values.database.port }}"
          - name: DB_NAME
            value: "{{ .Values.database.name }}"
          - name: DB_USERNAME
            value: "{{ .Values.database.username }}"
          - name: DB_PASSWORD
            value: "{{ .Values.database.password }}"