{{- if and .Values.localdb.enabled (not .Values.secret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jp.fullname" . }}
  labels:
    {{- include "jp.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials - from database config
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- with .Values.secret }}
  {{- range $key, $value := . }}
  {{- if and (ne $key "DB_USERNAME") (ne $key "DB_PASSWORD") }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}

