# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
      argocd.argoproj.io/sync-wave: "0"

spec:
  # ignoreDifferences:
  #   - group: admissionregistration.k8s.io
  #     kind: MutatingWebhookConfiguration
  #     jsonPointers:
  #       - /webhooks/0/clientConfig/caBundle
  #   - group: admissionregistration.k8s.io
  #     kind: ValidatingWebhookConfiguration
  #     jsonPointers:
  #       - /webhooks/0/clientConfig/caBundle
  #   - group: apps
  #     kind: DaemonSet
  #     name: kube-prometheus-stack-prometheus-node-exporter
  #     jsonPointers:
  #       - /spec/template/spec/containers/0/resources
  #   - group: apps
  #     kind: Deployment
  #     name: kube-prometheus-stack-grafana
  #     jsonPointers:
  #       - /spec/template/spec/containers/0/resources
  #       - /spec/template/spec/containers/1/resources
  project: default

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: gitops/apps/kube-prometheus-stack
    targetRevision: HEAD

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
