# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
{{- $stage := default "local" .Values.env.stage }}
{{- if ne $stage "prod" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
      argocd.argoproj.io/sync-wave: "0"

spec:
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: kube-prometheus-stack-admission
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: apps
      kind: DaemonSet
      name: kube-prometheus-stack-prometheus-node-exporter
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-grafana
      jqPathExpressions:
        - .spec.template.spec.containers[].resources

  project: default

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: gitops/apps/kube-prometheus-stack
    targetRevision: HEAD

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}