# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      name: loki-canary
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
    - group: apps
      kind: DaemonSet
      name: loki-promtail 
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
    - group: apps
      kind: StatefulSet
      name: loki
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
  
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: gitops/apps/loki
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-local.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
