# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
{{- $stage := default "local" .Values.env.stage }}
{{- if ne $stage "prod" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  project: default

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: gitops/apps/kubecost
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kubecost

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
{{- end }}
