apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: monitoring # 注意：通常要放喺同 Prometheus 同一個 NS，或者有標籤選取
  labels:
    release: kube-prometheus-stack # <--- 重要！睇下你個 Prometheus 裝嗰陣個 release name 係咩，通常係 'prometheus' 或 'kube-prometheus-stack'
spec:
  namespaceSelector:
    matchNames:
      - default  # <--- 改做你 Flask App 真正住緊嗰個 Namespace 名
  selector:
    matchLabels:
      app: app # <--- 這裡要對應返你 Flask Service 嘅 Label
  endpoints:
  - port: http-web # 對應 Service 入面 port 嘅名 (name: http-web)
    path: /metrics
    interval: 15s