apiVersion: v2
name: kubecost-wrapper
description: My Custom kubecost Wrapper Chart
type: application
version: 1.0.0

dependencies:
  - name: cost-analyzer
    version: 2.9.6 # 建議鎖定版本 (check 返最新 stable version)
    repository: https://kubecost.github.io/cost-analyzer/
