apiVersion: v2
name: kubecost-wrapper
description: My Custom kubecost Wrapper Chart
type: application
version: 1.0.0

dependencies:
  - name: cost-analyzer
    # helm search repo cost-analyzer -l | head -n 15
    version: 2.8.6 # 建議鎖定版本 (check 返最新 stable version)
    repository: https://kubecost.github.io/cost-analyzer/
