apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-svc
  namespace: default
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: app
  type: NodePort

