apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  # Flask secret key
  SECRET_KEY: "just-a-placeholder"

  # PostgreSQL credentials
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"

  # Mail server credentials (if MailHog doesn't require a password, you can omit this)
  # MAIL_USERNAME: <mail_user>
  # MAIL_PASSWORD: <mail_pass>

  # API Keys
  # GEMINI_API_KEY: <Gemini API Key>
