{
 "title": "Flask Monitoring",
 "description": "Flask Monitoring with StatsD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_http_request_total{}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (flask_http_request_total{service=~\"$service\"})"
    },
    {
     "expr": "sum (flask_http_request_total{service=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (flask_http_request_total{service=~\"$service\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    },
    {
     "expr": "sum (flask_http_request_total{service=~\"$service\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{service=~\"$service\"} / flask_http_request_duration_seconds_count{service=~\"$service\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{service=~\"$service\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{service=~\"$service\", status=~\"2.*\"}) by(endpoint, method) / sum(flask_http_request_total{service=~\"$service\"}) by(endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{service=~\"$service\", status=~\"5.*\"}) by(endpoint, method) / sum(flask_http_request_total{service=~\"$service\"}) by(endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{service=~\"$service\"} / flask_http_request_duration_seconds_count{service=~\"$service\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Duration Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds{service=~\"$service\", quantile='0.5'}"
    },
    {
     "expr": "flask_http_request_duration_seconds{service=~\"$service\", quantile='0.9'}"
    },
    {
     "expr": "flask_http_request_duration_seconds{service=~\"$service\", quantile='0.99'}"
    }
   ]
  }
 ]
}