apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fyp-app
  name: fyp-app
  namespace: default
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: fyp-app
  strategy: {}
  template:
    metadata:
      labels:
        app: fyp-app
    spec:
      containers:
      - image: yuemanwai/fyp-jp:latest
        name: fyp-jp
        # always pull the latest image (for development only)
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: fyp-app-secret
        - configMapRef:
            name: fyp-app-config
        # env:
        # - name: DB_HOST
        #   value: "db-svc.default.svc.cluster.local"
        # - name: DB_PORT
        #   value: "5432"
        # - name: DB_NAME
        #   value: "postgres"
        # - name: DB_USER
        #   value: "postgres"
        # - name: DB_PASSWORD
        #   value: "postgres"
        resources:
          requests:
            cpu: "0.1"
            memory: 256Mi
          limits:
            cpu: "0.5"
            memory: 512Mi
        ports:
        - containerPort: 5000
          protocol: TCP
        # Liveness Probe - 檢查應用是否存活
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Readiness Probe - 檢查應用是否就緒
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # # Startup Probe - 檢查應用啟動
        # startupProbe:
        #   httpGet:
        #     path: /startup
        #     port: 5000
        #   initialDelaySeconds: 0
        #   periodSeconds: 10
        #   timeoutSeconds: 3
        #   failureThreshold: 30