apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fyp-app
  name: fyp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fyp-app
  strategy: {}
  template:
    metadata:
      labels:
        app: fyp-app
    spec:
      containers:
      - image: yuemanwai/fyp-jp:latest
        name: fyp-jp
        env:
        - name: DB_HOST
          value: "db-svc.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.25"
            memory: 256Mi
        ports:
        - containerPort: 5000
          protocol: TCP