apiVersion: v1
kind: Service
metadata:
  labels:
    app: fyp-app
  name: fyp-app-svc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fyp-app
  type: NodePort

