kube-prometheus-stack:
  # 1. 關閉 Alertmanager (你自己做 Lab 唔洗發 Alert Email，慳好多 RAM)
  alertmanager:
    enabled: false

  # 2. 將 Grafana 變輕
  grafana:
    # 1. 既然手動睇到權限已經係 472，我哋就唔好俾佢再搞事
    initChownData:
      enabled: false

    # 2. 維持非 Root 運行，確保安全
    podSecurityContext:
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472
    enabled: true
    adminUser: admin
    adminPassword: "change-me-grafana-admin-password"
    persistence:
      enabled: true
      type: pvc
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    resources:
      limits:
        cpu: 300m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      type: NodePort
      nodePort: 32000
      targetPort: 3000
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL # 掃描所有 namespace
        resources:
          limits:
            memory: 512Mi
            cpu: 100m
          requests:
            memory: 256Mi
            cpu: 50m
    additionalDataSources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          timeout: 60s
          maxLines: 1000

  # 3. 大幅閹割 Prometheus
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false # 重要！等我哋自己定義嘅 recording rules 可以生效
      # 這是關鍵！Minikube 重啟數據無咗就算，唔好用 PV，用 RAM 做 Storage (快 + 慳 IO)
      # storageSpec:
      #   emptyDir:
      #     medium: Memory
      retention: 6h
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 512Mi

  # 4. 關閉一堆你暫時用唔著嘅 K8s 元件監控 (慳資源)
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  coreDns:
    enabled: false
  kubeProxy:
    enabled: false

  additionalPrometheusRulesMap:
    # 呢粒 key 你鍾意叫乜都得，通常叫 kubecost-rules
    kubecost-rules:
      additionalLabels:
        release: kube-prometheus-stack
        prometheus: kube-prometheus-stack # 有些版本會搵呢粒
        role: alert-rules
      groups:
        - name: kubecost.recording.rules
          rules:
            # 1. 針對無 container label 嘅數做補底
            - record: kubecost_container_cpu_usage_irate
              expr: sum(irate(container_cpu_usage_seconds_total{container="", pod!=""}[1m])) by (pod, namespace, node, cluster)
              labels:
                container: unknown

            # 2. 正常嘅計數 Rule
            - record: kubecost_container_cpu_usage_irate
              expr: sum(irate(container_cpu_usage_seconds_total{container!="", pod!=""}[1m])) by (container, pod, namespace, node, cluster)

            # 3. Memory 補底
            - record: kubecost_container_memory_working_set_bytes
              expr: sum(container_memory_working_set_bytes{container="", pod!=""}) by (pod, namespace, node, cluster)
              labels:
                container: unknown
kubelet:
  serviceMonitor:
    cAdvisor: true
    # 喺數據「入口」直接加 label
    metricRelabelings:
      - sourceLabels: [pod]
        targetLabel: container
        action: replace
