apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jp.fullname" . }}-db
  labels:
    {{- include "jp.labels" . | nindent 4 }}
    component: database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
