{{- if .Values.localdb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jp.fullname" . }}-db
  labels:
    {{- include "jp.labels" . | nindent 4 }}
    component: database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  serviceName: {{ include "jp.fullname" . }}-db
  # replicas: 1
  selector:
    matchLabels:
      {{- include "jp.selectorLabels" . | nindent 6 }}
      component: database
  template:
    metadata:
      labels:
        {{- include "jp.labels" . | nindent 8 }}
        component: database
    spec:
      containers:
      - image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        imagePullPolicy: {{ .Values.database.image.pullPolicy }}
        name: postgres
        envFrom:
        - secretRef:
            name: {{ include "jp.fullname" . }}-db
        - configMapRef:
            name: {{ include "jp.fullname" . }}-db
        {{- with .Values.database.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.database.port }}
          protocol: TCP
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  {{- if .Values.database.persistence.enabled }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgres-data
    spec:
      accessModes: [ {{ .Values.database.persistence.accessMode | quote }} ]
      resources:
        requests:
          storage: {{ .Values.database.persistence.size }}
  {{- end }}
{{- end }}