# ==========================================================
# ArgoCD Helm Chart
# ==========================================================

redis-ha:
  enabled: false

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

server:
  replicas: 1
  autoscaling:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus

repoServer:
  replicas: 1
  autoscaling:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus

applicationSet:
  enabled: false

dex:
  enabled: false

notifications:
  enabled: true
