apiVersion: v2
name: root-app
description: The Root Application that manages all other apps (App of Apps pattern)
type: application
version: 0.1.0 # 這是 Chart 本身的版本
appVersion: "1.0.0" # 這是 App 的版本 (在這個 context 下不太重要)
