apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fyp-app.fullname" . }}-db
  labels:
    {{- include "fyp-app.labels" . | nindent 4 }}
    component: database
data:
  POSTGRES_DB: "postgres"
