apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fyp-app.fullname" . }}-db
  labels:
    {{- include "fyp-app.labels" . | nindent 4 }}
    component: database
type: Opaque
stringData:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
