apiVersion: v1
kind: Service
metadata:
  name: {{ include "fyp-app.fullname" . }}-db
  labels:
    {{- include "fyp-app.labels" . | nindent 4 }}
    component: database
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    {{- include "fyp-app.selectorLabels" . | nindent 4 }}
    component: database
  type: ClusterIP
  clusterIP: None