apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jp.fullname" . }}-init-db
  labels:
    {{- include "jp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
spec:
  backoffLimit: {{ .Values.job.backoffLimitCount }}
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["/bin/sh", "-c", "python init_db.py && python test_data.py"]
        envFrom:
          - configMapRef:
              name: {{ include "jp.fullname" . }} # 讀取你的 App config
          - secretRef:
              name: {{ include "jp.fullname" . }} # 讀取你的 RDS 密碼
      restartPolicy: OnFailure
      imagePullPolicy: IfNotPresent