apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "jp.fullname" . }}
  labels:
    {{- include "jp.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "jp.selectorLabels" . | nindent 6 }}
      component: app