apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jp.fullname" . }}
  labels:
    {{- include "jp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

