{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "jp.fullname" . }}
  namespace: monitoring
  labels:
    {{- include "jp.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ .Chart.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "jp.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path | default "/metrics" }}
    interval: {{ .Values.serviceMonitor.interval | default "30s" }}

{{- end }}