apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    # 關鍵設定 1：告訴 Nginx 後端的 ArgoCD 是用 HTTPS 講野的
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # 關鍵設定 2：容許「透傳」HTTPS，直接用 ArgoCD 自己的證書 (這能避免很多 Redirect Loop 問題)
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https