# gitops/apps/loki/values-local.yaml

# 第一層：Wrapper Dependency Name (必須叫 loki)
loki:
  deploymentMode: SingleBinary

  # 第二層：Loki Chart 內部的 Config
  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    # 【關鍵 1】雖然用 Filesystem，但照填 Bucket Name 塞住 Helm 把口
    storage:
      type: "filesystem"
      bucketNames:
        chunks: "chunks" # 假的，不會真的用到 S3
        ruler: "ruler"
        admin: "admin"

    # 【關鍵 2】明確定義 Schema，指向 filesystem
    schemaConfig:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem # 這裡才是真正決定存去邊
          schema: v13
          index:
            prefix: index_
            period: 24h

  # 關閉 Local 不需要的功能
  minio:
    enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false

  # 讓 Loki 有位寫 File (Local Persistence)
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi

# Promtail 設定 (與 loki 同級)
promtail:
  enabled: true
  config:
    clients:
      - url: http://loki-loki:3100/loki/api/v1/push
